---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-example
  namespace: env-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        env1: dev
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: snaidu/rideeasy:v3
        ports:
          - containerPort: 8080
            protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-example
  namespace: env-qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
        env2: qa
    spec:
      containers:
      - name: tomcat
        image: snaidu/webapp:latest
        ports:
          - containerPort: 8080
            protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-example
  namespace: env-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
        env3: prod
    spec:
      containers:
      - name: tomcat
        image: snaidu/got:v2
        ports:
          - containerPort: 8080
            protocol: TCP
---
